### PR TITLE
Rely on a few official Jekyll plugins

### PR DESCRIPTION
**Pull request by benbalter**
:wave: @lee-dohm stumbled upon your site via your latest blog post, and thought it might benefit from using a few officially supported, Jekyll core plugins (that presumably have been released since you started the site). 

There's a few different things included here, but I broke them into atomic commits where I could, in case you wanted to cherry pick. Specifically:

* Use [Jemoji](https://github.com/jekyll/jemoji) instead of the custom emoji filter 
* Use [Jekyll redirect from](https://github.com/jekyll/jekyll-redirect-from) instead of the custom alias filter
* Use [Jekyll feed](https://github.com/jekyll/jekyll-feed) instead of the custom feed template
* Use [Jekyll SEO Tag](https://github.com/jekyll/jekyll-seo-tag) to output head and open graph metadata
* Add [Jekyll sitemap](https://github.com/jekyll/jekyll-sitemap)

If you're interested, glad to talk about the advantages of any of the above, but in short:

### Homepage before

screen shot 2016-08-04 at 12 10 46 pm

### Homepage after

screen shot 2016-08-04 at 12 11 50 pm

### Post before

screen shot 2016-08-04 at 12 12 18 pm

### Post after

screen shot 2016-08-04 at 12 12 33 pm

### Feed before

```xml

<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">

 <title>lee-dohm.com</title>
 <link href="http://www.lee-dohm.com/" rel="self"/>
 <link href="http://www.lee-dohm.com"/>
 <updated>2016-08-04T08:41:44-07:00</updated>
 <id>http://www.lee-dohm.com</id>
 <author>
   <name>Lee Dohm</name>
   <email>lee@lee-dohm.com</email>
 </author>

 
 <entry>
   <title>Phishing Evolved</title>
   <link href="http://www.lee-dohm.com/2016/08/04/phishing-evolved/"/>
   <updated>2016-08-04T08:40:49-07:00</updated>
   <id>http://www.lee-dohm.com/2016/08/04/phishing-evolved</id>
   <content type="html">&lt;p&gt;This is a description of a very sophisticated phishing scam that almost caught a professional unawares. I have to admit, I might also have been caught up in this if I was in the author&amp;rsquo;s shoes. This is why two-factor authentication is so important. A username and password combination is just too easy to break these days.&lt;/p&gt;
</content>
 </entry>
```

### Feed after

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xml" href="/feed.xslt.xml"?>
<feed xmlns="http://www.w3.org/2005/Atom">
   <generator uri="http://jekyllrb.com" version="3.0.1">Jekyll</generator>
   <link href="http://www.lee-dohm.com/feed.xml" rel="self" type="application/atom+xml" />
   <link href="http://www.lee-dohm.com/" rel="alternate" type="text/html" />
   <updated>2016-08-04T12:11:10-04:00</updated>
   <id>http://www.lee-dohm.com/</id>
   <title>lee-dohm.com</title>
   <subtitle>Games and Technology Should Include EVERYone</subtitle>
   <author>
      <name>Lee Dohm</name>
      <email>lee@lee-dohm.com</email>
   </author>
   <entry>
      <title>Phishing Evolved</title>
      <link href="http://www.lee-dohm.com/2016/08/04/phishing-evolved/" rel="alternate" type="text/html" title="Phishing Evolved" />
      <published>2016-08-04T11:40:49-04:00</published>
      <updated>2016-08-04T11:40:49-04:00</updated>
      <id>http://www.lee-dohm.com/2016/08/04/phishing-evolved</id>
      <content type="html" xml:base="http://www.lee-dohm.com/2016/08/04/phishing-evolved/">&lt;p&gt;This is a description of a very sophisticated phishing scam that almost caught a professional unawares. I have to admit, I might also have been caught up in this if I was in the author&amp;rsquo;s shoes. This is why two-factor authentication is so important. A username and password combination is just too easy to break these days.&lt;/p&gt;</content>
      <author>
         <name>Lee Dohm</name>
         <email>lee@lee-dohm.com</email>
      </author>
      <summary>This is a description of a very sophisticated phishing scam that almost caught a professional unawares. I have to admit, I might also have been caught up in this if I was in the author&amp;rsquo;s shoes. This is why two-factor authentication is so important. A username and password combination is just too easy to break these days.</summary>
   </entry>
```

### CODE REVIEW

**Comment by lee-dohm** [comment]
Thanks so much! Taking a look at it now :grinning:

**Comment by lee-dohm** [comment]
The feed doesn't seem to be working. All I'm getting is:

```
Atom Feed:http://www.lee-dohm.com/
updated:2016-08-04T09:32:38-07:00
title:lee-dohm.com
```

**Comment by benbalter** [comment]
> All I'm getting is:

It has a stylesheet so that it's human readable in browser (https://github.com/jekyll/jekyll-feed/pull/119) cURL of view source should show the XML.

**Comment by lee-dohm** [comment]
It still doesn't seem to be getting any of the articles:

```xml
<?xml version="1.0" encoding="utf-8"?><?xml-stylesheet type="text/xml" href="/feed.xslt.xml"?><feed xmlns="http://www.w3.org/2005/Atom"><generator uri="http://jekyllrb.com" version="3.0.1">Jekyll</generator><link href="http://www.lee-dohm.com/feed.xml" rel="self" type="application/atom+xml" /><link href="http://www.lee-dohm.com/" rel="alternate" type="text/html" /><updated>2016-08-04T09:32:38-07:00</updated><id>http://www.lee-dohm.com/</id><title>lee-dohm.com</title><subtitle>Games and Technology Should Include EVERYone</subtitle><author><name>Lee Dohm</name><email>lee@lee-dohm.com</email></author></feed>
```

**Comment by benbalter** [comment]
Hmm... It's working for me locally. Have you tried`bundle update`?

[Here's the template it uses](https://github.com/jekyll/jekyll-feed/blob/master/lib/feed.xml), which should just loop through `site.posts`.

**Comment by lee-dohm** [comment]
Ok, yeah `bundle update` did it. Thanks!

**Comment by benbalter** [comment]
:metal: Glad I could help! 😄

**Comment by Haroenv** [comment]
so awesome seeing one of the creators jump in and add things to Jekyll blogs

**Pull request merged**
